on:
  pull_request:
    types: [ closed ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: "20"
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
          username: ${{ secrets.GANDIUSERNAME }}
          server: ${{ secrets.GANDISERVER }}
          port: 22
          password: ${{ secrets.GANDIPASSWORD }}
          local_path: "./dist/*"
          remote_path: "vhsots/perrien.fr/htdocs/labs/pitchfork/"
          sftpArgs: '-o ConnectTimeout=5'